### ISSUE TITLE
Complete preliminary checks ("Foreløbig check færdiggøres")

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-GeoDanmarkCheck#24]
Reparerer koden til check af foreløbige objekter

**Comment by AsgerPetersen** [comment]
[Foreløbig_regel.pdf](https://github.com/Septima/qgis-GeoDanmarkCheck/files/519019/Forelobig_regel.pdf)
Flowchart for checks wrt prelim object

**Comment by AsgerPetersen** [comment]
Fixed in d98f9dac04fb60dfc8946044572aaab4ed036702
