### ISSUE TITLE
Island-test for vandløbsmidte ("Rettelse 4: Island-testen skal også udføres for ”Vandløbsmidte”)

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-GeoDanmarkCheck#28]
”Island”-testen skal udføres også for Vandløbsmidte. I første omgang uden attributbegrænsninger. Hvis det giver for mange uinteressante, kan der evt. filtreres på f.eks. ”Retning” efter nærmere aftale. Der er ikke andre attributter, der kan angive hovedvandløbene betrykkende.

**Comment by bjornharrtell** [comment]
Fungerar med befintlig NetworkIslands kontroll. Har lagt till konfiguration med samma parametrar som för `VEJMIDTE_BRUDT` dvs. `minlength` 500 och `minnodes` 10. För testdata Hjorring fastnar 1326 (av 14488) som fel med dessa parametrar, de kanske skall justeras?

**Comment by AsgerPetersen** [comment]
Det lyder som ret mange. Har du et indtryk af, om det er relevante fejl?

**Comment by bjornharrtell** [comment]
Jag tror nog `minlength` och ev. `minnodes` bör minskas men har ingen uppfattning om till vad. Det bästa vore kanske om dessa parametrar gick att justera i GUI? Bör hursomhelst kommuniceras med kund.
