### ISSUE TITLE
Can 'Geometri_status' legally be NULL?

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-GeoDanmarkCheck#33]
Seen in Thisted 'after' file. There are 709 of these in vejmidte_brudt?

**Comment by KurtToft** [comment]
NO, 'Geometri_status' and 'Object_status are mandatory.

**Comment by AsgerPetersen** [comment]
Ok. This is not checked for at the moment. Rules relying on the attribute to have a value for instance "geometri_status = endelig" will of course only see features where this condition is actually true.
