### ISSUE TITLE
New checker-control: Control digitizing direction of VANDLØBSMIDTE

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-GeoDanmarkCheck#34]
**Update på denne mail fra Kurt d. 18. oktober:**
Issue 34 ændres til at sammenligne en før- og en efter-fil med vandløbsmidter. Det undersøges, om kombinationen af digitaliseringsretning og attributten ”Retning” giver den samme resulterende flow-retning i efter-filen, som flowretningen var i før-filen

**TIDLIGERE - skal ikke implementeres**
Mail fra Kurt d. 6.oktober:
VANDLØBSMIDTE har en attribut kaldet ’Retning’.
Denne angiver, om vandet løber i samme retning som objektet er digitaliseret i:
Retning=1 modsat retning
Retning=0 samme retning
Hvis Retning ikke er angivet, opfattes det som om Retning=0.
For at kontrollere, om denne attribut er sat rigtigt, skal alle vandløb undersøges.
Vandløbsmidter med et tilnærmet fald på over ½ meter undersøges for at kontrollere, om kombinationen af digitaliseringsretning og retnings-attributten giver samme flowretning, som højdeforskellen angiver.
Udefineret z (-999.00) indgår ikke i beregningen af det tilnærmede fald
Skal udføres på enkelt fil uden støtte fra andre filer.

**Comment by bjornharrtell** [comment]
Retning för `VANDLOEBSMIDTE_BRUDT` saknas i `0787_Thisted_20160902.gml`. Vi försöker reda ut detta med Kurt.

**Comment by MieWinstrup** [comment]
Data til test der indeholder retningsdata findes her: https://drive.google.com/open?id=0B8JRpAZchq5-Vkx1UE1GM1ZNRzA

**Comment by bjornharrtell** [comment]
Jag tycker data ser ok ut, fortsätter med implementation av check.

**Comment by MieWinstrup** [comment]
Hvis der ikke er nogen kolonne  der hedder 'Retning' i filen, så antages at retning= null (dvs. samme retning som digitaliseringsretningen).
