### ISSUE TITLE
Undersøgelse af bug med tjek af data ved 'Building UUID unique'

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-GeoDanmarkCheck#35]
**Fra Kurts mail d. 27/10:**
Nu har jeg fundet en fil, der ikke kan checkkes
Når man kører filen, går QGIS ned med en fejl.
Hvad skyldes det. Er der fejl i filen (og hvad er fejlen) eller er der fejl i plugin-en.
 
Fejlen opstår, når man checkker for ”Building UUID unique”.

**Test hos septima**
Fejlen kan reproduceres på Mies computer med følgende dump-fil:

![image](https://cloud.githubusercontent.com/assets/16276034/20181217/8ee82a58-a75d-11e6-9c5c-14d87809009b.png)

**Comment by bjornharrtell** [comment]
@MieWinstrup vi vill ha "en fil" :)

**Comment by MieWinstrup** [comment]
Den ligger her:
https://drive.google.com/open?id=0B8JRpAZchq5-YXpnWHFGSWZpTVU

**Comment by bjornharrtell** [comment]
Tack! Jag flyttade den till https://drive.google.com/open?id=0BzqGxrJPNa3EWTVJMURGMmU0NXc eftersom det redan fanns en tidigare mapp för chekern.

**Comment by bjornharrtell** [comment]
Kan reproducera crashen i QGIS 2.14 på Debian.

**Comment by MieWinstrup** [comment]
Issue genåbnet, da der er en ny fil som får GeoDanmark-tjekker til at crashe.

**Kurt skriver (d. 21/11):**
Vi har fundet en fil mere, der ikke kan blive kontrolleret for unique building ID i Odsherred kommune. Vi har prøvet at køre GeoDanmark Checker v.1.1.0  på en fil, som kun indeholder bygninger og programmet går desværre stadigvæk ned.

**Test hos Mie**
QGIS: Version 2.16.3
GeoDanmarkChecker: Version 1.1
Resultat: QGIS crasher ved tjek af fil (Odsherred)

**Opgave:**
Finde ud af hvorfor QGIS crasher og fikse dette.
Fil til at teste ligger her:
https://drive.google.com/drive/folders/0B8JRpAZchq5-emlrenMzbnpYR28

**Comment by bjornharrtell** [comment]
Was missing in 1.1.0 release because I made a mixup in git when making the releasing. :(

**Comment by MieWinstrup** [comment]
That's okay. Now I can close this issue :)
