### ISSUE TITLE
Bug: Dublicate road centreline

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-GeoDanmarkCheck#38]
Der er fejl med tjekket: ”Dublicate road centreline”.

Der meldes fejl, når to vejobjekter passer sammen i begge deres ender, som vist her på billedet:

![image](https://cloud.githubusercontent.com/assets/16276034/20486647/cdbd2278-b000-11e6-8ceb-8dd4ce6635c7.png)
 
Det lyseblå objekt fejlmeldes.
 
Der er to fejl af denne type i filen for Jammerbugt der findes her:
https://drive.google.com/drive/folders/0ByBwEF3ObjMsekZPcmkwaG9vMUk

**Comment by AsgerPetersen** [comment]
Melder den ikke "Possible duplicate geometry"?

Der er ikke tale om en fuldstændig bulletproof test, så det kan ikke
undgås, at der kommer falske positiver. Men vi kan selvfølgelig arbejde med
_hvilke_ falske hits, der kommer.

**Comment by MieWinstrup** [comment]
Mail fra kurt d. 5/12:

Med hensyn til isseu38, så er de ”possible dublicate geometry” fejl, der er fundet, karakteriseret ved, at deres endepunkter passer eksakt sammen, mens mellempunkternes antal og placering slet ikke passer.
 
Forestil dig en gennemskåret krukke med låg: her passer krukkens kant fint med kanten af låget, mens forløbet af krukken og forløbet af låget slet ingen ligheder har ud over deres fælles berøringspunkter.
 
Det må være muligt at lave en forbedring til reglen, så de fremfundne kandidater til ”dublicate geometry” testes for deres maksimale afvigelse og/eller længde, for at se hvor ens de er.
De viste eksempler ville med en sådanne metode med sikkerhed kunne frasorteres som ”possible dublicate geometry”
