### ISSUE TITLE
Stream centrelines false positives

### ISSUE THREAD

**Issue by bjornharrtell** [Septima/qgis-GeoDanmarkCheck#45]
Suspected case is that SegmentMatcher matches start of new centreline on a close by original centreline depending on angle and distance.

**Comment by bjornharrtell** [comment]
Test data and marked false positives at https://drive.google.com/open?id=0BzqGxrJPNa3EVVROLTU4Z0EtVU0

**Comment by bjornharrtell** [comment]
Discussion with Asger results in proposal to add a check to a match:

1. Matched segment A against B
2. Try to match B against candidates
3. If A has a candidate closer than B ignore the original match

**Comment by bjornharrtell** [comment]
In the test data we have marked errors as false positives that are not in the strict sense. They are in cases where the topology has changed (i.e moved non isolated node) but this is out of scope for the actual check that was originally agreed upon (geometry segment match).

**Comment by bjornharrtell** [comment]
I have found that there are still two types of perceived false positives.

## Type 1
![typ1](https://cloud.githubusercontent.com/assets/141030/22293915/affac6d4-e311-11e6-883a-e61dc6ee0c13.png)

Type 1 is the common case which I and Flemming have discussed and that we can take care of.

Type 2:
![typ2](https://cloud.githubusercontent.com/assets/141030/22293925/b4962184-e311-11e6-84b8-cf1645ece3f9.png)

I have only found a single case of Type 2. This case looks like the the change is moving a "node" in the line topology. As the check is matching geometry without considering topology the segment is matched as an error. To eliminate this case a different more advanced topology aware check is required.

**Comment by bjornharrtell** [comment]
@KurtToft please read the comment above and get back to me if you agree that type 2 is something we will have to accept as false positives.

**Comment by KurtToft** [comment]
@bjornharrtell Don't do anything to solve this rare Type 2 case. This case will stay as a false positive.
